### PR TITLE
Fixed errors in document

### PR DESCRIPTION
**Pull request by mzeinstra**
This is a botched job of implementing our translations. Either you did not give us good instruction how to provide you with the translation or you did not have a look at the files you received.

Take a look at the edits and see if you can see recurring mistakes that are also in many other translations.

### CODE REVIEW

**Comment by mattl** [comment]
You'll need to update either the Google Document or the CSV file in https://github.com/creativecommons/sotc-2015/tree/master/translations for your language.

The other files are generated.

**Comment by mattl** [comment]
@janeatcc will provide you access to the spreadsheet where you can update this.

**Comment by janetpkr** [comment]
Maarten you should have access to the sheet and it's been shared with you
for your row.

On Wed, Dec 9, 2015 at 9:55 AM, Matt Lee notifications@github.com wrote:

> @janeatcc https://github.com/janeatcc will provide you access to the
> spreadsheet where you can update this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/sotc-2015/pull/110#issuecomment-163339848
> .

## 

Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by mzeinstra** [comment]
I have, I have fixed most of my errors.

I don't know how to translate 'This report is licensed ____ by Creative Commons' as the ____ are not replaced by the name of the license. Please advise.

Also the Wow! translation needs to be moved to the first part of the sentence.

**Comment by janetpkr** [comment]
That string was from the PDF version of the report, which Matt changed for
the web version. If you want, you can translate this string and put in that
field instead:

State of the Commons report 2015 is licensed under a Creative Commons

> Attribution 4.0 International License
> http://creativecommons.org/licenses/by/4.0/.

On Thu, Dec 10, 2015 at 2:09 AM, Maarten Zeinstra notifications@github.com
wrote:

> I have, I have fixed most of my errors.
> 
> I don't know how to translate 'This report is licensed ____ by Creative
> Commons' as the ____ are not replaced by the name of the license. Please
> advise.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/sotc-2015/pull/110#issuecomment-163563730
> .

## 

Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by mzeinstra** [comment]
Done.

**Comment by janetpkr** [comment]
Dutch translation edits done, ready to update.

**Pull request closed without merging**
